# Generated by Django 4.0.6 on 2022-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogusermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
